import type { Config } from "tailwindcss";

// AtelierSync 목업(space_requirement.txt / check_list.txt)의 tailwind.config 토큰을
// 100% 그대로 옮긴 것. 색·radius·spacing·폰트·폰트사이즈 변경 금지 — 스타일 동일성 보장.
const config: Config = {
  darkMode: "class",
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#e5e2de",
        "on-background": "#1c1c1a",
        "tertiary-fixed-dim": "#cdc5bc",
        error: "#ba1a1a",
        outline: "#73787a",
        "error-container": "#ffdad6",
        "surface-container-low": "#f6f3ef",
        "primary-container": "#1a2e35",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#1f1b15",
        "primary-fixed": "#d0e6ef",
        "secondary-fixed": "#e5e2de",
        "surface-container": "#f0ede9",
        secondary: "#5f5e5b",
        "on-secondary-fixed": "#1c1c1a",
        "surface-variant": "#e5e2de",
        "on-primary": "#ffffff",
        tertiary: "#1a1711",
        "tertiary-fixed": "#eae1d7",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "inverse-primary": "#b4cad3",
        "inverse-surface": "#31302e",
        "inverse-on-surface": "#f3f0ec",
        "on-tertiary-container": "#989289",
        "on-secondary-container": "#636260",
        "on-primary-fixed-variant": "#364a51",
        "on-surface": "#1c1c1a",
        "on-secondary-fixed-variant": "#474744",
        "surface-bright": "#fcf9f5",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#81969e",
        "on-surface-variant": "#42484a",
        "secondary-fixed-dim": "#c8c6c2",
        "primary-fixed-dim": "#b4cad3",
        "on-primary-fixed": "#091e25",
        "tertiary-container": "#2f2b24",
        "surface-dim": "#dcdad6",
        surface: "#fcf9f5",
        "secondary-container": "#e2dfdb",
        "surface-tint": "#4d6169",
        background: "#fcf9f5",
        "on-error-container": "#93000a",
        "outline-variant": "#c2c7ca",
        primary: "#041920",
        "surface-container-high": "#eae8e4",
        "on-tertiary-fixed-variant": "#4b463f",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        unit: "8px",
        "margin-mobile": "20px",
        "margin-desktop": "64px",
        gutter: "24px",
        "container-max": "1440px",
      },
      maxWidth: {
        "container-max": "1440px",
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        caption: ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "500" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" }],
        caption: ["12px", { lineHeight: "1.4", fontWeight: "400" }],
      },
      boxShadow: {
        soft: "0 4px 20px rgba(4, 25, 32, 0.05)",
      },
    },
  },
  plugins: [],
};

export default config;
